#!/usr/bin/env bash
# Installs HAproxy and configures it with roundrobin
sudo apt-get update
sudo apt-get install -y haproxy=1.5
sudo cp /etc/default/haproxy /etc/default/haproxy.bak
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.bak
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
config="frontend web-frontend\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tmode http\n\toption forwardfor\n\tserver 300-web-01 34.73.233.204:80 check\n\tserver 300-web-02 35.231.184.169:80 check\n"
echo -e $config | tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy reload
sudo service haproxy restart
