#!/usr/bin/env bash
#use the while loop and  the if, elif and else statements
n=1
while [ $n -le 10 ]
do
if [ $n -eq 4 ]
then
echo "bad luck"
elif [ $n -eq 8 ]
then
echo "good luck"
else
echo "Holberton School"
fi
n=$(( n + 1 ))
done
