#!/usr/bin/env bash
#use the while loop and  use the case statement
i=1
while [ $i -le 20 ]
do
echo $i
case $i in
4)
echo "bad luck from china"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
((n++))
esac
i=$(( i + 1 ))
done 
