#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes
n=0
while [ $n -le 12 ]
do
echo "Hour: $n"
i="1"
while [ $i -le 59 ]
do
echo "$i"
i=$((i + 1))
done
n=$((n + 1))
done
